'use client';

import { useState } from "react";
// import { Metadata } from "next";
import LayoutClient from "./layoutClient";
import { context } from "./context";

// export const metadata: Metadata = {
//     title: "My title",
//     description: "Generated by create next app",
// };


export default ({ children, searchParams }: { children: JSX.Element, searchParams: { name: string } }) => {
    console.log(`params : ${searchParams}`);
    console.log('router layout render');
    const [state, setState] = useState(0);

    return <div>
        router layout

        <br />
        <LayoutClient/>

        <div>
            {state}
            <button onClick={() => setState(state => state + 1)}>add</button>
            <context.Provider value={state}>
                {
                    children
                }
            </context.Provider>
        </div>
    </div>
}